# Generated by Django 5.1.1 on 2024-09-16 05:23

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.IntegerField(default=34536436, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='specialist',
            name='phone',
            field=models.IntegerField(default=36436367, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email name already exists.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Inventory Manager'), (3, 'Inventory Specialist'), (1, 'admin')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer, Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator], verbose_name='username'),
        ),
    ]
